name: Push

on:
  push:
    branches:
      - dev
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      released_version: ${{ steps.release.outputs.released_version }}

    steps:
      - id: release
        uses: agrc/release-composite-action@v1
        with:
          prerelease: ${{ github.ref_name == 'dev' }}
          release-type: node
          extra-files: manifest.json
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          github-app-id: ${{ vars.UGRC_RELEASE_BOT_APP_ID }}
          github-app-key: ${{ secrets.UGRC_RELEASE_BOT_APP_KEY }}
          github-app-name: ${{ vars.UGRC_RELEASE_BOT_NAME }}
          github-app-email: ${{ vars.UGRC_RELEASE_BOT_EMAIL }}
